services:

  redis:
    image: redis:latest
    container_name: redis-rate-limiter
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: app-rate-limiter
    ports:
      - "8080:8080"
    depends_on:
      - redis